/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 */
val junit5Version = "5.5.0"
val archUnitVersion = "0.11.0"

plugins {
    id("org.jetbrains.kotlin.jvm").version("1.3.21")

    application
}

repositories {
    jcenter()
}

dependencies {
    // Use the Kotlin JDK 8 standard library.
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")
    testImplementation("org.jetbrains.kotlin:kotlin-test")
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit")
    testCompile("org.assertj:assertj-core:3.12.2")
    testCompile("org.junit.jupiter:junit-jupiter:$junit5Version")
    testCompile("junit:junit:4.12")

}

tasks.test {
    useJUnitPlatform()
}

application {
    // Define the main class for the application.
    mainClassName = "clean-code-workshop.FromRomanChar"
}

